spring:
  application:
    name: automatedworkstation
  datasource:
    driver-class-name: org.postgresql.Driver
    username: test
    password: ae9623
    url: jdbc:postgresql://localhost:5432/axiomatic