spring:
  thymeleaf:
    cache: false
  application:
    name: automatedworkstation
  datasource:
    driver-class-name: org.postgresql.Driver
    username: test
    password: ae9623
    url: jdbc:postgresql://localhost:5432/axiomatic
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: :true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
